general:
    eventlogger: 127.0.0.1:7197
    dc_files:
        - ../dclass/otp.dc
        - ../dclass/pirates.dc

messagedirector:
    bind: 127.0.0.1:7199

uberdogs:
    - class: CentralLogger
      id: 4688
      anonymous: false

    - class: ClientServicesManager
      id: 4665
      anonymous: true

    - class: DistributedAvatarManager
      id: 4674
      anonymous: false

roles:
    - type: clientagent
      bind: 0.0.0.0:6667
      version: "sv-1.0.0"
      manual_dc_hash: "0xDEADBEEF"
      client:
       relocate: true
       add_interest: enabled
      channels:
        min: 1000000000
        max: 1009999999

    - type: stateserver
      control: 10000

    - type: database
      control: 4008
      generate:
        min: 100000000
        max: 399999999
      backend:
        type: yaml
        foldername: databases/astrondb

    - type: dbss
      database: 4008
      ranges:
        - min: 100000000
          max: 399999999

    - type: eventlogger
      bind: 127.0.0.1:7197
      output: logs/events-%y%m%d_%H%M%S.log
      
