id: 100000001
class: DistributedPlayerPirate
fields:
  setDISLid: (100000000)
  WishName: ([])
  setDNAString: (<fd0001070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000010000000000000000000000000000000000000001000000000000000000000000000000000000000100000000000000000000000000000000000000010000000000000000000000000000000000000001000000000000000000000000000000000000000100000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000>)
  setName: ("Pirate")
  WishNameState: ("OPEN")
  setAdminAccess: (400)
  setBadgeIcon: (0, 0)
  setShipBadgeIcon: (0, 0)
  setInventoryId: (0)
  setMaxHp: (4950)
  setHp: (50, 0)
  setMaxLuck: (100)
